package middleware

import (
	_ "embed"
	"encoding/json"
	"math"
	"net/http"
	"regexp"
	"strings"
)

// BotCategory represents the type of bot detected.
type BotCategory string

const (
	BotCategorySearchEngine BotCategory = "SEARCH_ENGINE"
	BotCategorySocial       BotCategory = "SOCIAL"
	BotCategoryMonitoring   BotCategory = "MONITORING"
	BotCategoryAICrawler    BotCategory = "AI_CRAWLER"
	BotCategoryScraper      BotCategory = "SCRAPER"
	BotCategoryAutomated    BotCategory = "AUTOMATED"
	BotCategoryUnknown      BotCategory = "UNKNOWN"
	BotCategoryHuman        BotCategory = "HUMAN"
)

// BotDetectionResult holds the result of bot detection.
type BotDetectionResult struct {
	IsBot      bool        `json:"isBot"`
	Category   BotCategory `json:"category"`
	Name       string      `json:"name,omitempty"`
	Confidence float64     `json:"confidence"`
	Signals    []string    `json:"signals"`
}

// BotProtectionOptions configures the bot protection middleware.
type BotProtectionOptions struct {
	Allow         []BotCategory // Categories to always allow (default: SEARCH_ENGINE, SOCIAL, MONITORING)
	Deny          []BotCategory // Categories to always deny (default: AUTOMATED)
	DefaultAction string        // "allow" or "deny" for uncategorized bots (default: "allow")
	StatusCode    int           // HTTP status for denied bots (default: 403)
	Message       string        // Denial message (default: "Access denied.")
}

const maxUALength = 2048

// botPatternsJSON is the slim runtime corpus, embedded at build time from
// arcis/packages/arcis-go/data/bot_patterns.json. Regenerate that file via
// `python packages/core/generate-bot-patterns.py` after upgrading the source
// arcjet/well-known-bots checkout.
//
//go:embed data/bot_patterns.json
var botPatternsJSON []byte

type botPattern struct {
	id        string
	name      string
	category  BotCategory
	accepted  []*regexp.Regexp
	forbidden []*regexp.Regexp
}

type botPatternRaw struct {
	ID        string   `json:"id"`
	Name      string   `json:"name"`
	Category  string   `json:"category"`
	Patterns  []string `json:"patterns"`
	Forbidden []string `json:"forbidden"`
}

// botPatterns is populated once at package init from the embedded JSON.
// ALL accepted patterns must match (multi-pattern entries like iMessage
// Preview only fire when every token is in the UA) and any forbidden
// pattern matching disqualifies the entry. `(?i)` prefix makes each regex
// case-insensitive — matches the Node + Python SDKs' contract.
var botPatterns []botPattern

func init() {
	var raw []botPatternRaw
	if err := json.Unmarshal(botPatternsJSON, &raw); err != nil {
		// The data file ships with the package and is generated by our own
		// tooling. A parse failure here is a build-time bug, not a runtime
		// concern — leave botPatterns empty so DetectBot still functions.
		return
	}
	out := make([]botPattern, 0, len(raw))
	for _, e := range raw {
		entry := botPattern{
			id:       e.ID,
			name:     e.Name,
			category: BotCategory(e.Category),
		}
		ok := true
		for _, src := range e.Patterns {
			re, err := regexp.Compile("(?i)" + src)
			if err != nil {
				ok = false
				break
			}
			entry.accepted = append(entry.accepted, re)
		}
		if !ok {
			continue
		}
		for _, src := range e.Forbidden {
			re, err := regexp.Compile("(?i)" + src)
			if err != nil {
				continue
			}
			entry.forbidden = append(entry.forbidden, re)
		}
		out = append(out, entry)
	}
	botPatterns = out
}

// DetectBot analyzes a request to determine if it's from a bot.
func DetectBot(r *http.Request) BotDetectionResult {
	ua := r.Header.Get("User-Agent")

	// Truncate to prevent CPU abuse
	if len(ua) > maxUALength {
		ua = ua[:maxUALength]
	}

	// 1. Pattern matching: ALL accepted regexes must match, none forbidden.
	for _, p := range botPatterns {
		if len(p.accepted) == 0 {
			continue
		}
		allMatched := true
		for _, re := range p.accepted {
			if !re.MatchString(ua) {
				allMatched = false
				break
			}
		}
		if !allMatched {
			continue
		}
		forbidden := false
		for _, re := range p.forbidden {
			if re.MatchString(ua) {
				forbidden = true
				break
			}
		}
		if forbidden {
			continue
		}
		return BotDetectionResult{
			IsBot:      true,
			Category:   p.category,
			Name:       p.name,
			Confidence: 0.95,
			Signals:    []string{"user_agent_match"},
		}
	}

	// 2. Behavioral signal analysis
	var signals []string

	if ua == "" {
		signals = append(signals, "missing_user_agent")
	}
	if r.Header.Get("Accept") == "" {
		signals = append(signals, "missing_accept")
	}
	if r.Header.Get("Accept-Language") == "" {
		signals = append(signals, "missing_accept_language")
	}
	if r.Header.Get("Accept-Encoding") == "" {
		signals = append(signals, "missing_accept_encoding")
	}
	if strings.ToLower(r.Header.Get("Connection")) == "close" {
		signals = append(signals, "connection_close")
	}

	if len(signals) >= 3 {
		confidence := math.Min(1.0, 0.6+float64(len(signals))*0.1)
		return BotDetectionResult{
			IsBot:      true,
			Category:   BotCategoryUnknown,
			Confidence: confidence,
			Signals:    signals,
		}
	}

	// 3. Human
	confidence := math.Max(0.0, 1.0-float64(len(signals))*0.15)
	return BotDetectionResult{
		IsBot:      false,
		Category:   BotCategoryHuman,
		Confidence: confidence,
		Signals:    signals,
	}
}

// BotProtection creates an http.Handler middleware that blocks or allows bots based on options.
func BotProtection(opts *BotProtectionOptions) func(http.Handler) http.Handler {
	o := defaultBotProtectionOptions()
	if opts != nil {
		if len(opts.Allow) > 0 {
			o.Allow = opts.Allow
		}
		if len(opts.Deny) > 0 {
			o.Deny = opts.Deny
		}
		if opts.DefaultAction != "" {
			o.DefaultAction = opts.DefaultAction
		}
		if opts.StatusCode > 0 {
			o.StatusCode = opts.StatusCode
		}
		if opts.Message != "" {
			o.Message = opts.Message
		}
	}

	allowSet := make(map[BotCategory]bool)
	for _, c := range o.Allow {
		allowSet[c] = true
	}
	denySet := make(map[BotCategory]bool)
	for _, c := range o.Deny {
		denySet[c] = true
	}

	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			result := DetectBot(r)

			if !result.IsBot {
				next.ServeHTTP(w, r)
				return
			}

			if allowSet[result.Category] {
				next.ServeHTTP(w, r)
				return
			}

			if denySet[result.Category] {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(o.StatusCode)
				w.Write([]byte(`{"error":"` + o.Message + `"}`))
				return
			}

			// Uncategorized bot
			if o.DefaultAction == "deny" {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(o.StatusCode)
				w.Write([]byte(`{"error":"` + o.Message + `"}`))
				return
			}

			next.ServeHTTP(w, r)
		})
	}
}

func defaultBotProtectionOptions() BotProtectionOptions {
	return BotProtectionOptions{
		Allow:         []BotCategory{BotCategorySearchEngine, BotCategorySocial, BotCategoryMonitoring},
		Deny:          []BotCategory{BotCategoryAutomated},
		DefaultAction: "allow",
		StatusCode:    http.StatusForbidden,
		Message:       "Access denied.",
	}
}
