package middleware

import (
	_ "embed"
	"encoding/json"
	"math"
	"net/http"
	"regexp"
	"strings"
	"sync"
	"sync/atomic"
)

// BotCategory represents the type of bot detected.
type BotCategory string

const (
	BotCategorySearchEngine    BotCategory = "SEARCH_ENGINE"
	BotCategorySocial          BotCategory = "SOCIAL"
	BotCategoryMonitoring      BotCategory = "MONITORING"
	BotCategoryAICrawler       BotCategory = "AI_CRAWLER"
	BotCategoryScraper         BotCategory = "SCRAPER"
	BotCategorySecurityScanner BotCategory = "SECURITY_SCANNER"
	BotCategoryAutomated       BotCategory = "AUTOMATED"
	BotCategoryUnknown         BotCategory = "UNKNOWN"
	BotCategoryHuman           BotCategory = "HUMAN"
)

// BotDetectionResult holds the result of bot detection.
type BotDetectionResult struct {
	IsBot      bool        `json:"isBot"`
	Category   BotCategory `json:"category"`
	Name       string      `json:"name,omitempty"`
	Confidence float64     `json:"confidence"`
	Signals    []string    `json:"signals"`
}

// BotProtectionOptions configures the bot protection middleware.
type BotProtectionOptions struct {
	Allow         []BotCategory // Categories to always allow (default: SEARCH_ENGINE, SOCIAL, MONITORING)
	Deny          []BotCategory // Categories to always deny (default: AUTOMATED)
	DefaultAction string        // "allow" or "deny" for uncategorized bots (default: "allow")
	StatusCode    int           // HTTP status for denied bots (default: 403)
	Message       string        // Denial message (default: "Access denied.")
}

const maxUALength = 2048

// botPatternsJSON is the slim runtime corpus, embedded at build time from
// arcis/packages/arcis-go/data/bot_patterns.json. Regenerate that file via
// `python packages/core/generate-bot-patterns.py` after upgrading the source
// arcjet/well-known-bots checkout.
//
//go:embed data/bot_patterns.json
var botPatternsJSON []byte

type botPattern struct {
	id        string
	name      string
	category  BotCategory
	accepted  []*regexp.Regexp
	forbidden []*regexp.Regexp
}

type botPatternRaw struct {
	ID        string   `json:"id"`
	Name      string   `json:"name"`
	Category  string   `json:"category"`
	Patterns  []string `json:"patterns"`
	Forbidden []string `json:"forbidden"`
}

// botPatternsAtomic holds the live []botPattern. Read lock-free in DetectBot
// (request goroutines) via Load; replaced wholesale by MergeBotPatterns (the
// Phase C cloud refresh, a background goroutine) via Store. The atomic swap
// keeps reads race-free without a per-request lock.
//
// ALL accepted patterns must match (multi-pattern entries like iMessage
// Preview only fire when every token is in the UA) and any forbidden pattern
// matching disqualifies the entry. `(?i)` prefix makes each regex
// case-insensitive — matches the Node + Python SDKs' contract.
var (
	botPatternsAtomic  atomic.Value // []botPattern
	bundledBotPatterns []botPattern
	mergeMu            sync.Mutex // serializes concurrent merges
)

func currentBotPatterns() []botPattern {
	v := botPatternsAtomic.Load()
	if v == nil {
		return nil
	}
	return v.([]botPattern)
}

func compileBotEntry(id, name, category string, patterns, forbidden []string) (botPattern, bool) {
	entry := botPattern{id: id, name: name, category: BotCategory(category)}
	for _, src := range patterns {
		re, err := regexp.Compile("(?i)" + src)
		if err != nil {
			return botPattern{}, false
		}
		entry.accepted = append(entry.accepted, re)
	}
	for _, src := range forbidden {
		re, err := regexp.Compile("(?i)" + src)
		if err != nil {
			continue
		}
		entry.forbidden = append(entry.forbidden, re)
	}
	return entry, true
}

func init() {
	var raw []botPatternRaw
	if err := json.Unmarshal(botPatternsJSON, &raw); err != nil {
		// The data file ships with the package and is generated by our own
		// tooling. A parse failure here is a build-time bug, not a runtime
		// concern — leave the corpus empty so DetectBot still functions.
		botPatternsAtomic.Store([]botPattern{})
		return
	}
	out := make([]botPattern, 0, len(raw))
	for _, e := range raw {
		if entry, ok := compileBotEntry(e.ID, e.Name, e.Category, e.Patterns, e.Forbidden); ok {
			out = append(out, entry)
		}
	}
	bundledBotPatterns = out
	botPatternsAtomic.Store(out)
}

// BotCorpusEntry is the wire shape of a cloud-served bot-corpus entry, accepted
// by MergeBotPatterns. Matches the bundled corpus JSON fields.
type BotCorpusEntry struct {
	ID        string
	Name      string
	Category  string
	Patterns  []string
	Forbidden []string
}

// MergeBotPatterns merges cloud-fetched bot-corpus entries on top of the live
// corpus (Phase C cloud refresh). New ids are appended; existing ids are
// replaced. An entry with an uncompilable pattern is skipped (fail-open). It
// builds a new slice and swaps it in atomically, so concurrent DetectBot reads
// never see a torn corpus. Returns the number merged.
func MergeBotPatterns(entries []BotCorpusEntry) int {
	mergeMu.Lock()
	defer mergeMu.Unlock()

	next := append([]botPattern(nil), currentBotPatterns()...)
	merged := 0
	for _, e := range entries {
		compiled, ok := compileBotEntry(e.ID, e.Name, e.Category, e.Patterns, e.Forbidden)
		if !ok {
			continue
		}
		replaced := false
		for i := range next {
			if next[i].id == compiled.id {
				next[i] = compiled
				replaced = true
				break
			}
		}
		if !replaced {
			next = append(next, compiled)
		}
		merged++
	}
	botPatternsAtomic.Store(next)
	return merged
}

// ResetBotPatternsForTest restores the bundled corpus, dropping cloud-merged
// entries. Test hook — not for production use.
func ResetBotPatternsForTest() {
	mergeMu.Lock()
	defer mergeMu.Unlock()
	botPatternsAtomic.Store(append([]botPattern(nil), bundledBotPatterns...))
}

// DetectBot analyzes a request to determine if it's from a bot.
func DetectBot(r *http.Request) BotDetectionResult {
	ua := r.Header.Get("User-Agent")

	// Truncate to prevent CPU abuse
	if len(ua) > maxUALength {
		ua = ua[:maxUALength]
	}

	// 1. Pattern matching: ALL accepted regexes must match, none forbidden.
	for _, p := range currentBotPatterns() {
		if len(p.accepted) == 0 {
			continue
		}
		allMatched := true
		for _, re := range p.accepted {
			if !re.MatchString(ua) {
				allMatched = false
				break
			}
		}
		if !allMatched {
			continue
		}
		forbidden := false
		for _, re := range p.forbidden {
			if re.MatchString(ua) {
				forbidden = true
				break
			}
		}
		if forbidden {
			continue
		}
		return BotDetectionResult{
			IsBot:      true,
			Category:   p.category,
			Name:       p.name,
			Confidence: 0.95,
			Signals:    []string{"user_agent_match"},
		}
	}

	// 2. Behavioral signal analysis
	var signals []string

	if ua == "" {
		signals = append(signals, "missing_user_agent")
	}
	if r.Header.Get("Accept") == "" {
		signals = append(signals, "missing_accept")
	}
	if r.Header.Get("Accept-Language") == "" {
		signals = append(signals, "missing_accept_language")
	}
	if r.Header.Get("Accept-Encoding") == "" {
		signals = append(signals, "missing_accept_encoding")
	}
	if strings.ToLower(r.Header.Get("Connection")) == "close" {
		signals = append(signals, "connection_close")
	}

	if len(signals) >= 3 {
		confidence := math.Min(1.0, 0.6+float64(len(signals))*0.1)
		return BotDetectionResult{
			IsBot:      true,
			Category:   BotCategoryUnknown,
			Confidence: confidence,
			Signals:    signals,
		}
	}

	// 3. Human
	confidence := math.Max(0.0, 1.0-float64(len(signals))*0.15)
	return BotDetectionResult{
		IsBot:      false,
		Category:   BotCategoryHuman,
		Confidence: confidence,
		Signals:    signals,
	}
}

// BotProtection creates an http.Handler middleware that blocks or allows bots based on options.
func BotProtection(opts *BotProtectionOptions) func(http.Handler) http.Handler {
	o := defaultBotProtectionOptions()
	if opts != nil {
		if len(opts.Allow) > 0 {
			o.Allow = opts.Allow
		}
		if len(opts.Deny) > 0 {
			o.Deny = opts.Deny
		}
		if opts.DefaultAction != "" {
			o.DefaultAction = opts.DefaultAction
		}
		if opts.StatusCode > 0 {
			o.StatusCode = opts.StatusCode
		}
		if opts.Message != "" {
			o.Message = opts.Message
		}
	}

	allowSet := make(map[BotCategory]bool)
	for _, c := range o.Allow {
		allowSet[c] = true
	}
	denySet := make(map[BotCategory]bool)
	for _, c := range o.Deny {
		denySet[c] = true
	}

	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			result := DetectBot(r)

			if !result.IsBot {
				next.ServeHTTP(w, r)
				return
			}

			if allowSet[result.Category] {
				next.ServeHTTP(w, r)
				return
			}

			if denySet[result.Category] {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(o.StatusCode)
				w.Write([]byte(`{"error":"` + o.Message + `"}`))
				return
			}

			// Uncategorized bot
			if o.DefaultAction == "deny" {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(o.StatusCode)
				w.Write([]byte(`{"error":"` + o.Message + `"}`))
				return
			}

			next.ServeHTTP(w, r)
		})
	}
}

func defaultBotProtectionOptions() BotProtectionOptions {
	return BotProtectionOptions{
		Allow:         []BotCategory{BotCategorySearchEngine, BotCategorySocial, BotCategoryMonitoring},
		Deny:          []BotCategory{BotCategoryAutomated},
		DefaultAction: "allow",
		StatusCode:    http.StatusForbidden,
		Message:       "Access denied.",
	}
}
